### ISSUE TITLE
Crash on iOS with RhoMobile 7.3.1

### ISSUE THREAD

**Issue by kpeterssolid** [rhomobile/rhodes#1061]
I'm running RhoMobile 7.3.1 on macOS 10.15.7 Catalina with Xcode 12.3 testing on a new iPhone SE 2020.  When I run my app, it crashes at startup.

Here's the relevant part of the crash log:
Thread 10 Crashed:
0   libsystem_kernel.dylib        	0x00000001be3b9414 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001dbe12b40 pthread_kill + 272
2   libsystem_c.dylib             	0x0000000199965b74 abort + 104
3   rhorunner                     	0x0000000100fbc26c rb_bug_context + 6390380 (error.c:443)
4   rhorunner                     	0x0000000100fbc2f0 rb_bug_errno + 6390512 (error.c:459)
5   rhorunner                     	0x00000001010e69d0 sig_do_nothing + 7612880 (signal.c:945)
6   libsystem_platform.dylib      	0x00000001dbe0d290 _sigtramp + 56
7   rhorunner                     	0x000000010103e6f0 rb_f_eval + 6924016 (vm_eval.c:1440)
8   rhorunner                     	0x000000010103e680 vm_exec + 6923904 (vm.c:1864)
9   rhorunner                     	0x000000010104fbe0 vm_call0_body + 6994912 (vm_eval.c:185)
10  rhorunner                     	0x000000010103b368 vm_call0 + 6910824 (vm_eval.c:64)
11  rhorunner                     	0x0000000101050b28 rb_call0 + 6998824 (vm_eval.c:357)
12  rhorunner                     	0x000000010103c2f0 rb_call + 6914800 (vm_eval.c:643)
13  rhorunner                     	0x000000010103c418 rb_funcall + 6915096 (vm_eval.c:841)
14  rhorunner                     	0x0000000100fbab58 callFramework + 6384472 (rhoruby.c:1131)
15  rhorunner                     	0x0000000100dcdc44 rho::net::CHttpServer::decide(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rho::Vector<rho::net::HttpHeader> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 4365380 (HttpServer.cpp:1929)
16  rhorunner                     	0x0000000100dcb610 rho::net::CHttpServer::process(int) + 4355600 (HttpServer.cpp:1219)
17  rhorunner                     	0x0000000100dcb050 rho::net::CHttpServer::run() + 4354128 (HttpServer.cpp:820)
18  rhorunner                     	0x0000000100ef9ea4 rho::common::CRhodesApp::run() + 5594788 (RhodesApp.cpp:585)
19  rhorunner                     	0x0000000100db0758 rho::common::CRhoThread::runObject() + 4245336 (RhoThread.h:70)
20  rhorunner                     	0x0000000100dc8c80 rho::common::runProc(void*) + 4344960 (PosixThreadImpl.cpp:66)
21  libsystem_pthread.dylib       	0x00000001dbe11b40 _pthread_start + 320
22  libsystem_pthread.dylib       	0x00000001dbe1a768 thread_start + 8

Is there something that I can do to work around or fix this issue?

**Comment by alex-epifanoff** [comment]
@kpeterssolid  seems like we need a code sample from you to reproduce the issue
