### ISSUE TITLE
fcm-push error rake aborted

### ISSUE THREAD

**Issue by charlyR** [rhomobile/rhodes#1075]
Building an app with fcm-push for Android, with latest google-services.json gets a rake aborted error.
It seems that if you dont use firebase database the google-services.json file doesnt contains the firebase_url key.
The problem is on the Rakefile for fcm-push on line 146.

add_data_to_string("firebase_database_url", "firebase_url") if $jsonfile

To solve this problem you have to manually add the firebase_url under project_info in google-services.json file, with any content you want, to complete the build.

**Comment by alex-epifanoff** [comment]
fixed with https://github.com/rhomobile/rhodes/commit/07161cca58ff6a960bbd1b79b36447b819bfa0eb
