### ISSUE TITLE
Too many field references to fit in one dex file

### ISSUE THREAD

**Issue by jurinco** [rhomobile/rhodes#1094]
I am using rhodes 7.4 and everything is Ok.

I want to use the last rhodes 7.5, but it seems that my app requires multidex support.

I am using barcode and I have a plugin that requires this libraries:
    - 'com.google.android.gms:play-services-location:19.0.0'
    - 'androidx.work:work-runtime:2.6.0'
    - 'androidx.constraintlayout:constraintlayout:1.1.3'
    - "androidx.recyclerview:recyclerview:1.2.1"

Error:
trouble writing output: Too many field references to fit in one dex file: 73261; max is 65536.
You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large.

How can I enable multidex support?

**Comment by jurinco** [comment]
Yes, I update to build-tools  version 32

**Comment by alex-epifanoff** [comment]
We're looking into if we can/need to enable multidex in Rhodes build system. Meanwhile did you try steps described here?

**Comment by hramovnik** [comment]
@jurinco could you please provide your build.yml. Basically I need your minsdk and targetsdk.

**Comment by jurinco** [comment]
@hramovnik minsdk is 23

android:
  minSDK: 23
  targetSDK: 31

so with this minsdk using rake device:android:production multiple classesN.dex files are generated?

**Comment by jurinco** [comment]
yes, thanks for the help.

**Comment by alex-epifanoff** [comment]
@jurinco FWIF, a patch for the issue was provided. Pending for the stable build.

**Comment by jurinco** [comment]
It is very interesting to support multidex, when will it be integrated into the master code? I have also had problems with https, version 7.7.0 mentions some changes in this regard? Is it in the master now?
