### ISSUE TITLE
Camera::get_camera_info retuns wrong resolution on Galaxy S3

### ISSUE THREAD

**Issue by LacioDrom** [rhomobile/rhodes#148]
Trying to return main camera resolution on Samsung Galaxy S3 (Android Version 4.0.4), I've got this bad result:

width = 640
height = 480

but main camera resolution is 3264x2448 !!!!

Here the code:

main_info = Camera.get_camera_info("main")

width = main_info['max_resolution']['width']
height = main_info['max_resolution']['height']

Alert.show_popup("Camera width " + width.to_s())
Alert.show_popup("Camera height " + height.to_s())

**Comment by alex-epifanoff** [comment]
Fixed with latest RMS 5.5 and 6.0 versions.
http://tau-technologies.com/developers/downloads/
