### ISSUE TITLE
sqlite3.c missing

### ISSUE THREAD

**Issue by tharry** [rhomobile/rhodes#191]
I've done: _rhodes-setup_

<pre>
JDK path (required) (): /usr/lib/jvm/java-6-oracle
Android SDK path (blank to skip) (): /home/harry/android/android-sdk-linux
Android NDK path (blank to skip) (/home/harry/android/android-ndk-r9_64): /home/harry/android/android-ndk-r9
Windows Mobile 6 SDK CabWiz (blank to skip) (): 
BlackBerry JDE 4.6 (blank to skip) (): 
BlackBerry JDE 4.6 MDS (blank to skip) (): 
BlackBerry JDE 4.2 (blank to skip) (): 
BlackBerry JDE 4.2 MDS (blank to skip) (): 
</pre>

And when running _rake run:android_ on new project i get:

<pre>
cd /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12
$app_config['extensions'] : ["json", "another-extension"]
$app_config['capabilities'] : []
$vendor = rhomobile
$app_package_name = com.rhomobile.storemanager
NDK sysroot: /home/harry/android/android-ndk-r9/platforms/android-14/arch-arm
mkdir -p /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/platform/android/bin
common_bundle_start
rm -rf /home/harry/rho/storemanager/bin/RhoBundle
mkdir -p /home/harry/rho/storemanager/bin/RhoBundle
mkdir -p /home/harry/rho/storemanager/bin/RhoBundle/lib
mkdir -p /home/harry/rho/storemanager/bin/RhoBundle/apps
cd lib/framework
cp -rp rhom.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rhom /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rbconfig.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp ostruct.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rholang /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp find.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp time.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp date.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rational.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp version.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rational18.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rhodes.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp indifferent_access.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rationalME.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rhodes-framework.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rho.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rho /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rhosystem.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp base64.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp dateOrig.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rhoframework.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rhomotoapi.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp date /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp dateME.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp singleton.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rhofsconnector.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp res /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp builtinME.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp rhoappmanifest.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp erb.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp bsearch.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -rp stringio.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cd /home/harry/rho/storemanager/bin/RhoBundle/lib
rm rhodes-framework.rb
rm erb.rb
rm find.rb
rm builtinME.rb
rm dateME.rb
rm rationalME.rb
cd /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12
init extensions
ext - json
add_extension - /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/lib/extensions/json - /home/harry/rho/storemanager/bin/RhoBundle/lib
cd /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/lib/extensions/json
cp -r json /home/harry/rho/storemanager/bin/RhoBundle/lib
cp -r json.rb /home/harry/rho/storemanager/bin/RhoBundle/lib
cd /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12
extyml /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/lib/extensions/json/ext.yml
ext - another-extension
exception
exts /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/platform/shared/ruby/ext/rho/extensions.c
cd /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12
cp -rp /home/harry/rho/storemanager/app /home/harry/rho/storemanager/bin/RhoBundle/apps
cp -rp /home/harry/rho/storemanager/public /home/harry/rho/storemanager/bin/RhoBundle/apps
cd /home/harry/rho/storemanager/bin/RhoBundle/apps
rm app/Settings/login.bb.erb
rm app/Settings/reset.bb.erb
rm app/Settings/wait.bb.erb
rm app/Settings/home.bb.erb
rm app/Settings/index.bb.erb
rm app/index.bb.erb
cd /home/harry/rho/storemanager/bin/RhoBundle/lib/res
rm blue_pushpin.wm.png
rm callout.wm.png
rm esri.wm.png
rm callout_link.wm.png
rm forward_btn.wm.png
rm back_btn.wm.png
rm home_btn.wm.png
rm options_btn.wm.png
rm refresh_btn.wm.png
rm blue_pushpin_small.wm.png
cd /home/harry/rho/storemanager/bin/RhoBundle
cd /home/harry/rho/storemanager/bin/RhoBundle/apps
cd /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12
cp lib/build/compileERB/default.rb /home/harry/rho/storemanager/bin/RhoBundle
Running default.rb

rm /home/harry/rho/storemanager/bin/RhoBundle/default.rb
cp lib/build/compileRB/compileRB.rb /home/harry/rho/storemanager/bin/RhoBundle
Running compileRB

cd /home/harry/rho/storemanager/bin/RhoBundle
rm apps/app/Settings/controller.rb
rm apps/app/helpers/browser_helper.rb
rm apps/app/helpers/application_helper.rb
rm apps/app/application.rb
rm lib/rhom.rb
rm lib/rhom/rhom.rb
rm lib/rhom/rhom_db_adapter.rb
rm lib/rhom/rhom_model.rb
rm lib/rhom/rhom_object.rb
rm lib/rhom/rhom_object_factory.rb
rm lib/rhom/rhom_source.rb
rm lib/rbconfig.rb
rm lib/ostruct.rb
rm lib/rholang/rhoerror_de.rb
rm lib/rholang/localization_simplified.rb
rm lib/rholang/rhomsg_es.rb
rm lib/rholang/rhomsg_en.rb
rm lib/rholang/rhomsg_de.rb
rm lib/rholang/lang_en.rb
rm lib/rholang/rhomsg_it.rb
rm lib/rholang/rhoerror_en.rb
rm lib/rholang/lang_es.rb
rm lib/rholang/rhoerror_es.rb
rm lib/time.rb
rm lib/date.rb
rm lib/rational.rb
rm lib/json/pure.rb
rm lib/json/pure/generator.rb
rm lib/json/version.rb
rm lib/json/common.rb
rm lib/version.rb
rm lib/rational18.rb
rm lib/rhodes.rb
rm lib/indifferent_access.rb
rm lib/json.rb
rm lib/rho.rb
rm lib/rho/rhoutils.rb
rm lib/rho/rhoevent.rb
rm lib/rho/rhoapplication.rb
rm lib/rho/rhobluetooth.rb
rm lib/rho/mapview.rb
rm lib/rho/rhotoolbar.rb
rm lib/rho/rhocontact.rb
rm lib/rho/render.rb
rm lib/rho/rhonativeviewmanager.rb
rm lib/rho/rhosupport.rb
rm lib/rho/rhoevent_c.rb
rm lib/rho/rho.rb
rm lib/rho/rhoerror.rb
rm lib/rho/rhotabbar.rb
rm lib/rho/rhoevent_bb.rb
rm lib/rho/rhofsconnector.rb
rm lib/rho/rhocontroller.rb
rm lib/rho/rhoviewhelpers.rb
rm lib/rho/rhomsg.rb
rm lib/rhosystem.rb
rm lib/base64.rb
rm lib/dateOrig.rb
rm lib/rhoframework.rb
rm lib/rhomotoapi.rb
rm lib/date/format.rb
rm lib/singleton.rb
rm lib/rhofsconnector.rb
rm lib/rhoappmanifest.rb
rm lib/bsearch.rb
rm lib/stringio.rb
rm compileRB.rb
rm apps/app/Settings/wait.erb
rm apps/app/Settings/home.erb
rm apps/app/Settings/reset.erb
rm apps/app/Settings/err_sync.erb
rm apps/app/Settings/index.erb
rm apps/app/Settings/login.erb
rm apps/app/layout.erb
rm apps/app/index.erb
cd /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12
cp -r platform/shared/db/res/db /home/harry/rho/storemanager/bin/RhoBundle
json is processing...
Checking extpath: /home/harry/rho/storemanager/extensions/json/ext
Checking extpath: /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/lib/extensions/json/ext
another-extension is processing...
Checking extpath: /home/harry/rho/storemanager/extensions/another-extension/ext
Checking extpath: /home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/lib/extensions/another-extension/ext
Extensions' java source lists: {}
{"audio"=>false, "camera"=>false, "gps"=>false, "network_state"=>true, "phone"=>false, "pim"=>false, "record_audio"=>false, "vibrate"=>false, "bluetooth"=>false, "calendar"=>false, "sdcard"=>false, "push"=>false, "motorola"=>false, "motoroladev"=>false, "webkit_browser"=>false, "shared_runtime"=>false, "motorola_browser"=>false}
No need to regenerate genconfig.h
No need to regenerate rhocaps.inc
rm -rf /home/harry/rho/storemanager/bin/tmp/assets
mkdir -p /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/apps /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/db /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/lib /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/apps /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/db /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/lib /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/hash /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/name /home/harry/rho/storemanager/bin/tmp/assets
cp -rp /home/harry/rho/storemanager/bin/RhoBundle/rho.dat /home/harry/rho/storemanager/bin/tmp/assets
mkdir -p /home/harry/rho/storemanager/bin/tmp/sqlite
mkdir -p /home/harry/rho/storemanager/bin/target/android/release/sqlite
/home/harry/android/android-ndk-r9/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-gcc --sysroot /home/harry/android/android-ndk-r9/platforms/android-14/arch-arm -fPIC -Wall -Wextra -Wno-psabi -Wno-sign-compare -mandroid -DANDROID -DOS_ANDROID -DRHO_DEBUG -g -O2 -DNDEBUG -Wall -Wextra -Wno-unused -I"/home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/platform/android/../shared/sqlite" -I"/home/harry/.rvm/gems/ruby-2.0.0-p195/gems/rhodes-3.5.1.12/platform/android/../shared" -c "platform/shared/sqlite/sqlite3.c" -o "/home/harry/rho/storemanager/bin/tmp/sqlite/sqlite3.c.o"
arm-linux-androideabi-gcc: "platform/shared/sqlite/sqlite3.c": No such file or directory
arm-linux-androideabi-gcc: no input files
</pre>

the file is there, and running command from gem dir finishes with warnings.

How should i build my project?

**Comment by alex-epifanoff** [comment]
Latest RMS versions runs OK with Ruby 2.3.x
