### ISSUE TITLE
Network Download File Progress Problem

### ISSUE THREAD

**Issue by gelinger777** [rhomobile/rhodes#206]
Hi All, I am raising this issue, because it's very fatal and vital for any App Developer. 
Problem is Following.  When there is bigger file to download from server, we have a NEED , or I would say a Requirement to show the progress of download to the user for usability purposes.  We have tries to find a solution by touching and getting the size of dinamic file 

filename.extention.rhodownload 

But the problem is on Rhosimulator is working, but on iOS happens following. what was obtained first time with Network.FileSize  on next call stays, so  somehow the same value stays.  That's the problem that we cannot use this approach. It's a NEED to have a small callback or  a call where from we can get the actual status of the download. 
Can we put this in your timeline?

**Comment by alex-epifanoff** [comment]
@gelinger777 Sorry for the such late answer. Rhomobile is now developed by Tau Technologies and we are working on resolution of many issues and doing our best to respond to platform users feedback. Yes, the date would be immediately written to storage so file size will reflect actual size of data received.
We could also implement a callback mechanizm to notify the app when portion of data was received - if you are still interested.

**Comment by gelinger777** [comment]
Good that you took it back over. :)  A good implementation of Download with callback mechanism to show progress and re-download when network is down or when connection is broken would be a good feature to have .

**Comment by alex-epifanoff** [comment]
We have this one in the backlog. As we are providing paid support, requests from paid customers have higher priority than from community.
For support options you may emails us to info@tau-technologies.com
For community support please register at forums.tau-technologies.com

**Comment by alex-epifanoff** [comment]
@gelinger777 please see
https://github.com/rhomobile/rhodes/pull/951
