### ISSUE TITLE
Database Import/Export

### ISSUE THREAD

**Issue by dimkagfx** [rhomobile/rhodes#235]
Hello,

We have encountered several problems while dealing with import/export methods.
Rhodes gem version ~> 3.5.1.13

``` ruby
Rhom::Rhom.database_import("#{@partition}", "#{@path}")
```

Import works fine, however, it requires to restart the application to reload models. I've tried to reload them manually using

``` ruby
Rho::RHO.get_instance().load_model('#{@model_name}')
```

With no results - Class exists, but any call (method "find" in this example) to this class results in a:

``` html
        <html>
2               <head>
3                   <meta name="viewport" content="width=320"/>
4               </head>
5               <body>
6                   <h2>Server Error</h2>
7                   <p>
8   Error: undefined method `[]' for nil:NilClass<br/>Trace: <br/>
9   C:/MotorolaRhoMobileSuite2.2.1.13/ruby/lib/ruby/gems/1.9.1/gems/rhodes-3.5.1.13/lib/framework/rhom/rhom_object_factory.rb:184:in `is_schema_source'<br/>
10  C:/MotorolaRhoMobileSuite2.2.1.13/ruby/lib/ruby/gems/1.9.1/gems/rhodes-3.5.1.13/lib/framework/rhom/rhom_object_factory.rb:838:in `find'<br/>
11  C:/Users/dmitri.suhhomjatniko/workspace/ECMK_MobileApp/app/Rdsap/rdsap_controller.rb:157:in `pcdf_search'<br/>
12  C:/MotorolaRhoMobileSuite2.2.1.13/ruby/lib/ruby/gems/1.9.1/gems/rhodes-3.5.1.13/lib/framework/rho/rhocontroller.rb:104:in `serve'<br/>
13  C:/MotorolaRhoMobileSuite2.2.1.13/ruby/lib/ruby/gems/1.9.1/gems/rhodes-3.5.1.13/lib/framework/rho/rhoapplication.rb:248:in `serve'<br/>
14  C:/MotorolaRhoMobileSuite2.2.1.13/ruby/lib/ruby/gems/1.9.1/gems/rhodes-3.5.1.13/lib/framework/rho/rho.rb:883:in `serve'                </p>    
15              </body>
16          </html>
17          
```

It is bearable, but a little bit inconvenient.

Export issues:

``` ruby
Rhom::Rhom.database_export("#{@partition}")
```

Export works well for partitions under 10mb. When it exceeds that size - no errors are being thrown and no zip file is created.

If there is a workaround for that problems I would really appreciate to hear it.

Thanks

**Comment by deepalits** [comment]
@dimkagfx Have you found any solution for this?

**Comment by alex-epifanoff** [comment]
What is Rhodes version you are using? Current stable version is 5.5.0.24, we recommend to use it.

**Comment by deepalits** [comment]
Tested with 5.5.0.24 but its not working. I noticed, post importing DB it is able to find the record but unable to update it.

I debugged it further hash_props is nil when accessed from check_freezing_model method.

Attached is the screenshot of error I get. 
![refresh](https://cloud.githubusercontent.com/assets/2361790/26043432/abc0aa30-395a-11e7-91ff-4f8e4a0b3d01.png)

**Comment by rognar** [comment]
Hi Dmitri,

Tau Technologies provides paid Rho support. If you are interested please mail to krybas@tau-technologies.com

Regards,
Konstantin
