### ISSUE TITLE
can't display twitter timeline

### ISSUE THREAD

**Issue by istar** [rhomobile/rhodes#269]
I’m planing to add twitter-timeline to my page.

let's simple, just add iframe on page(http://k-rudy.github.io/phonegap-twitter-timeline/?410453165654278145). any other website can display normal, but twitter-timeline always have problem.

I debug on Xcode: 

(BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request
navigationType:(UIWebViewNavigationType)navigationType {

NSLog(@"%@", request);

the result:

I 01/19/2014 21:04:05:693 ac564a28 SimpleMainView| WebView shouldStartLoadWithRequest( about:blank )

I 01/19/2014 21:04:05:693 ac564a28 SimpleMainView| Open url in external application: about:blank

I don't know why about:blank here, anyone who knows why?

**Comment by vmusulainen** [comment]
Closed as obsoleted
