### ISSUE TITLE
UnderOS Methodology Consideration

### ISSUE THREAD

**Issue by ylluminate** [rhomobile/rhodes#271]
Nikolay who is making UnderOS at the moment has some very smart approaches that you may consider incorporating in his creation of that framework, please review: 
• http://vimeo.com/82808469
• http://under-os.com
• https://github.com/under-os/under-os

The feel and workflow for this is fantastic and perhaps something you should aim for with Rhodes as well as it seems to be what many of us would like.

**Comment by alex-epifanoff** [comment]
Seems to  be a dead project by now.
