### ISSUE TITLE
Update QT Webkit for Win32 and RhoSim to the latest QT Webkit

### ISSUE THREAD

**Issue by cfh463** [rhomobile/rhodes#273]
It seems like the version of Webkit as reported by Rho.System.webviewFramework (2.2.2) is quite behind. The current version is 5.x. Can we update it so RhoSimulator and Win32 builds use the latest.

**Comment by alex-epifanoff** [comment]
RMS 6.0 released by Tau now uses QT 5.8 for Win32 and RhoSim.
Chrome debug tools are supported.
http://tau-technologies.com/developers/downloads/
