### ISSUE TITLE
Getting Unwanted Confirm Box (JS Prompt) while navigating using Selendroid

### ISSUE THREAD

**Issue by motobhakta** [rhomobile/rhodes#286]
Getting unwanted JS Prompt while any calls happen using selendroid Inside WebView.

In Log :
I/APP     (20459): I 03/29/2014 14:02:56:367 00004feb    RhoExtManagerImpl| Execute JS hook: {"method":"databaseFilePath","params":["app"],"__rhoClass":"Rho.Application","__rhoID":"0","jsonrpc":"2.0","id":4}

I/APP     (20459): I 03/29/2014 14:02:56:368 00004feb    RhoExtManagerImpl| JS result: {"jsonrpc": "2.0", "result":"/data/data/com.rhomobile.compliancetest_js/rhodata/db/syncdbapp.sqlite", "id": 4}

I/APP     (20459): I 03/29/2014 14:02:56:369 00004feb   RhoWebChromeClient| JS Prompt is processing by rhodes: true

![screenshot_2014-03-29-11-41-55](https://cloud.githubusercontent.com/assets/3646744/2558110/0245f2d2-b733-11e3-92b7-aaf2367f4bae.png)

**Comment by alex-epifanoff** [comment]
@randoum please use latest RMS versions released by Tau Technologies.
http://tau-technologies.com/developers/downloads/
