### ISSUE TITLE
Installation of Rhomobile suite on clean Mavericks!

### ISSUE THREAD

**Issue by gelinger777** [rhomobile/rhodes#314]
Dear All!
I had some  complications on installing the suite in fresh MAvericks. 

First of all  I want to mention that as per your documentation we should have Ruby 1.9.3 

When we try to install via RVM the Ruby 1.9.3 We are requested to have 

gcc46 , which is as I have found out was removed from the  MacOS and need to be installed extra. GCC installation usually takes very long and in the end we also get message that the Ruby 1.9.3 is no more maintained and buggy.   

There is option to make build with cland but it also can lead to segfaults . 

So can you please update if the  newer or newest  version of ruby can be used to install rhomobile?

**Comment by alex-epifanoff** [comment]
@gelinger777 Latest RMS versions supported by Tau Technologies are working OK with Ruby 2.3.x
http://tau-technologies.com/developers/downloads/
