### ISSUE TITLE
Rhodes open camera is very slow on Android 4.2, but 4.0 4.4 is OK.

### ISSUE THREAD

**Issue by liyaozong** [rhomobile/rhodes#335]
The issue is found in rhodes 3.5 stable
I track the bug into platform/shared/net/HttpServer.cpp file,

bool CHttpServer::receive_request(ByteVector &request)
{
    for(;;) {
                if(++attempts > 100)
                {
                    RAWLOG_ERROR("Error when receiving data from socket. Client does not send data for 10 sec. Cancel recieve.");
                    return false;
                }

```
            fd_set fds;
            FD_ZERO(&fds);
            FD_SET(m_sock, &fds);

            timeval tv = {0};
            tv.tv_usec = 100000;//100 MS

            select(m_sock + 1, &fds, 0, 0, &tv);
            continue;
        }
```

}

The request which is http get method "/system/uidestroyed" will be send to server. But the receive_request() function of HttpServer cannot get the request immediately， it waste 10 seconds about.

**Comment by alex-epifanoff** [comment]
Please use latest RMS versions available at Tau's downloads
http://tau-technologies.com/developers/downloads/
