### ISSUE TITLE
Consistent use of version strings/include git SHA in source

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#359]
Lately, the use of version strings and labeling of commits (branches, tags) in the Git repo has become inconsistent. There is no reliable way of correlating a "released" Rhodes Gem ("released" = "included in Rhomobile Suite download") with a particular Git commit.

This is important to developers for any number of reasons.
- Developer may be required to conduct a security audit. This is impossible without being able to correlate to the repo, check-out, and self-build.
- Developer may want/need to know exactly what changes were made between two versions. Release notes are nice. repo history is reliable.
- Developer might want to be informed by checkin comments as to why a particular change was made.
- etc. etc. etc. Basically, the repo is useless if you cannot correlate it to the release that you are using.

Can you please follow a consistent version-labeling scheme, document it, and follow it faithfully? That will help, but is not the ultimate solution.

Currently, 
- `master` branch has version label `4.1.1`, and is under active development. 
- `5-0-stable` branch has version label `5.0.0` and has minimal activity. It hasn't had activity in about a month.
- The current "release" has version label `5.0.2` and I can find no commit that has that version label.
- Previously, each release was (more-or-less, with some exceptions) tagged with a git tag with the numeric version. Except when it was tagged with the prefix "r" and the numeric version. (Yes, there have been two tags with the same version number on different commits...)

Among other things, this leads to the current situation where "edge" documentation says it's for `4.1`, while the current release is `5.0.2`.

It is apparent, as well, that the release process must include checking-out some commit (which? That is the question I am trying to answer...) and then manually updating the `version` file prior to building the Gem. (I guess there is a desire for all of the components to have the same version number, e.g. `5.0.2` for current release).

When I say _version label_, I mean the `version` file in the root directory. This becomes part of the Gem name, is baked-into Rhodes code, etc.

It "would be nice" to straighten this out so that the version numbers make some sense.

What would be nicer would be to stamp Rhodes with a full git SHA so that there is never any question where a particular source came from. (To audit, you could check-out that commit by SHA, build the Gem, then compare.)

I'd suggest adding some file in the root directory similar to `version`. Call it `git_sha` "git_hash`,`git_info`, etc.

As well, this value should be baked-into the Gem and into Rhodes `System`. You should be able to retrieve it at run-time just like you can the version. This is a more definitive, fool-proof way than relying on the version string.

We do something similar with our own apps. Feel free to ask questions. You can use `git` command-line tools to integrate this into your build process.

**Comment by alex-epifanoff** [comment]
@jtara Curently we have following branch/versions correlation:

master - active development branch gathering new features pull requests and bugfixes. 6.0.x versions are made from it.
6-0-stable - a 6.0 branch which only collects important fixes and some features required by customers. 6.0.0.x versions are made from it.
5-5-stable - a 5.5 support branch which only collects important fixes and some features required by customers. Used for 5.5.0.x versions.

We make lables in above branches for the released versions.
