### ISSUE TITLE
cannot run application

### ISSUE THREAD

**Issue by maki5** [rhomobile/rhodes#362]
I installed the gem setup paths to jdk, sdk, ndk. The sdk, and ndk are unarchived, but when I run rake run:android:device a have this error

cd /home/maki/.rvm/gems/ruby-1.9.3-p429@rh/gems/rhodes-3.5.1.12
$app_config['extensions'] : ["json", "another-extension"]
$app_config['capabilities'] : []
$vendor = rhomobile
$app_package_name = com.rhomobile.storemanager
rake aborted!
Can't detect NDK toolchain path (corrupted NDK installation?)
/home/maki/.rvm/gems/ruby-1.9.3-p429@rh/gems/rhodes-3.5.1.12/platform/android/build/androidcommon.rb:88:in `setup_ndk'
/home/maki/.rvm/gems/ruby-1.9.3-p429@rh/gems/rhodes-3.5.1.12/platform/android/build/android.rake:388:in`block (2 levels) in <top (required)>'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:246:in`block in execute'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:241:in`execute'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:177:in`invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in`each'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:183:in`block in invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:205:in`block in invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in`invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:177:in`invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in`each'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:183:in`block in invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:205:in`block in invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in`invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:177:in`invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in`each'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:183:in`block in invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/task.rb:170:in`invoke'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:101:in`block (2 levels) in top_level'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:101:in`block in top_level'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:95:in`top_level'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/home/maki/.rvm/gems/ruby-1.9.3-p429@global/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/home/maki/.rvm/gems/ruby-1.9.3-p429@rh/bin/ruby_noexec_wrapper:14:in`eval'
/home/maki/.rvm/gems/ruby-1.9.3-p429@rh/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => run:android:device => device:android:debug => package:android => build:android:all => build:android:rhobundle => config:android

**Comment by alex-epifanoff** [comment]
@maki5 latest Rhodes gem works OK with Ubuntu, and latest Android SDK/NDK are supported at the moment.
http://tau-technologies.com/developers/downloads/
