### ISSUE TITLE
Iphone simulator is not working stuck on splash screen

### ISSUE THREAD

**Issue by sabarinathancs** [rhomobile/rhodes#412]
Iphone simulator is not working stuck on splash screen 

System Contains
No rhoElements
Mac os 10.10
xcode 6.1
rhostudio 4.1.1
ruby 1.9.3
rvm
node

build.yml bold**
sdkversion: "4.1.0"
name: "E-Undi"
version: "1.0"
vendor: "UniversityOfMalya"
build: "release"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator7.1"
  provisionprofile:
  codesignidentity: "iPhone Developer"
  entitlements:
  BundleIdentifier: "com.um.e-undi"
  BundleURLScheme: "e-undi"
  emulatortarget: "7.1"
env:
  app: "/Users/isis/store"
wp8:
  productid: "02a870a0-21c2-0132-d4d2-0260a0061001"
android:
  manifest_template: "AndroidManifest.erb"
  version: "4.0"
  package_name: "com.um.eundi"
extensions:
- rhoconnect-client
- coreapi
  capabilities:
- gps
- pim
- phone
  sdk: "/Users/isis/.rvm/gems/ruby-1.9.3-p547/gems/rhodes-4.1.1"

![screen shot 2014-10-22 at 10 21 42 pm](https://cloud.githubusercontent.com/assets/5072200/4749837/3269f300-5a8a-11e4-8532-30cd014a1ba7.png)

**Other Error Trying to simulator bold**

cd /Users/isis/.rvm/gems/ruby-1.9.3-p547/gems/rhodes-4.1.1

*\* Execute run:buildsim

UIApplicationExitsOnSuspend not configured, using default of false

kill "iPhone Simulator"

No matching processes belonging to you were found

No matching processes belonging to you were found

mkdir -p /Users/isis/Library/Application Support/iPhone Simulator/8.1

mkdir -p /Users/isis/Library/Application Support/iPhone Simulator/8.1/Applications/6B4AE59D-0838-4530-BFDC-6D30F9AF43AC/Documents

mkdir -p /Users/isis/Library/Application Support/iPhone Simulator/8.1/Applications/6B4AE59D-0838-4530-BFDC-6D30F9AF43AC/Library/Preferences

mkdir -p /Users/isis/Library/Application Support/iPhone Simulator/8.1/Applications/6B4AE59D-0838-4530-BFDC-6D30F9AF43AC/Library/Caches/Private Documents

rm -rf /Users/isis/Library/Application Support/iPhone Simulator/8.1/Applications/6B4AE59D-0838-4530-BFDC-6D30F9AF43AC/rhorunner.app

cp -r /Users/isis/Desktop/E-Undi/project/iphone/build/Debug-iphonesimulator/rhorunner.app /Users/isis/Library/Application Support/iPhone Simulator/8.1/Applications/6B4AE59D-0838-4530-BFDC-6D30F9AF43AC

rhorunner: /Users/isis/Desktop/E-Undi/project/iphone/build/Debug-iphonesimulator/rhorunner.app

our app name: E-Undi

simdir: /Users/isis/Library/Application Support/iPhone Simulator/

app guid: 6B4AE59D-0838-4530-BFDC-6D30F9AF43AC

rm -f /Users/isis/Desktop/E-Undi/rholog.txt

rm -f /Users/isis/Desktop/E-Undi/sim-public-8.1

*\* Execute run:iphone

mkdir -p /Users/isis/Desktop/E-Undi/project/iphone/bin/tmp

kill "iPhone Simulator"

No matching processes belonging to you were found

No matching processes belonging to you were found

start thread with execution of application

use old execution way - just open iPhone Simulator

The file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone Simulator.app does not exist.

**Comment by alex-epifanoff** [comment]
@sabarinathancs Please use latest RMS released by Tau Technologies.
It supports all new XCode and iOS versions.
http://tau-technologies.com/developers/downloads/
