### ISSUE TITLE
Rho::Network.get() POSTs if body is present

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#415]
`Rho::Network.get` apparently ignores the HTTP verb and always does POST if a body is present. This is true even if `httpVerb` is explicitly set to `GET` in options.

It should be possible to do a GET with a body! It is common in REST interfaces. (Even if you are GETing, an interface might require some authentication, etc. in body.)

Note that it is possible to use other verbs. e.g. I can PUT by using `Rho::Network.get()` or `Rho::Network.post()` with `httpVerb` set to PUT.

There does seem to be some ambiguity with regard to standards:

http://stackoverflow.com/questions/978061/http-get-with-request-body

Unfortunately, I have to work with an API that has perhaps colored outside of the lines.

I am using Rhodes 5.0.2.

**Comment by alex-epifanoff** [comment]
It is documented behavior, closing.
http://docs.tau-technologies.com/en/5.5/api/Network#mget
