### ISSUE TITLE
Rho.Log.showLog() does not work on Android with RMS 5.0.2-sp2 branch as of 12/7/14

### ISSUE THREAD

**Issue by nhinze** [rhomobile/rhodes#436]
When I use "Rho.Log.showLog()" in Javascript (or ruby) to show the log in my Android app, it does not show the log. Actually nothing happens and there is no error message. It worked fine in RMS 5.0.2.

RMS 5.0.2-sp2 branch as of 12/7/2014
Android 4.2.2 to 4.4.4
minSDK 17
Android SDK 4.4.2
Android NDK 10d

**Comment by alex-epifanoff** [comment]
Working OK with latest RMS versions.
