### ISSUE TITLE
Please tag released versions in git

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#444]
Please tag version 5.0.25 (and future versions!) in the git repo, so that we may know exactly what commit corresponds to the release.

If we want/need to refer to source code, it is important to know exactly what commit corresponds to the released software.

As well, the `version` file should be updated in the repo. Apparently, it is changed as part of the build process when creating RhoMobile Suite, but often not subsequently checked-in.  It is still "5.0.2" in current head.

**Comment by alex-epifanoff** [comment]
We are tagging now versions officially released by Tau
