### ISSUE TITLE
iOS 8.1 GPS problem with Rhodes 5.0.0

### ISSUE THREAD

**Issue by maridansoft** [rhomobile/rhodes#451]
Hi Guys, 
want to take to your attention following problem. 

I have an application with Leaflet JS and it has in it leaflet geolocation plugin
https://github.com/domoritz/leaflet-locatecontrol
Formerly the app was working with iOS 7.0 and from inside app it was using the native browser(Safari's)  location properties, and the app was showing the person location. Now despite the fact that I have in the build.yml properties section -gps listed either that plugin via browser  or the Ruby version of geolocation  are not working. The callback is firing but the app is not requesting  users permision to get the location and location sign is not becoming active. What's up? Who can help?

**Comment by maridansoft** [comment]
I have found Paul  Goh's Answer to the problem at

https://developer.motorolasolutions.com/thread/29682 

suggesting 


>Hi Siddhant,
 
>Your post was earlier in the month, so you may have found a work around already.
>GeoLocation API needs some changes to work with IOS 8.0. This post I found online explains the >changes to the LocationManager in IOS 8.x SDK quite well is http://nevan.net/2014/09/core-location->manager-changes-in-ios-8/
 
>Workaround that we are using for now is, updating the initLocationManger method in ><XcodeProjectPath>/Classes/GeoLocation/LocationController.m as below:
 
>- (void) initLocationManager:(NSObject*)param {
 
>    self._locationManager = [[[CLLocationManager alloc] init] autorelease];
>    self._locationManager.desiredAccuracy = kCLLocationAccuracyBest;
>    self._locationManager.delegate = self; // Tells the location manager to send updates to this object
 
>    // Workaround for IOS 8 SDK LocationManager changes
  >  if ([self._locationManager respondsToSelector:@selector(requestAlwaysAuthorization)]) {
  >      [self._locationManager requestAlwaysAuthorization];
>    }
}
 
>and updating Info.plist file with string values for NSLocationAlwaysUsageDescription and >NSLocationWhenInUseUsageDescription.
 
>A formal fix would be ideal, but I haven't seen if something like this has made into Rhodes GIT repo >or Rho 5.x
>Would be great to hear if there are any other solutions / workarounds for this.

**Comment by dmitrys** [comment]
fixed
https://github.com/rhomobile/rhodes/commit/427cfa880915046fb27e5237a87cafeaf60b60ca
