### ISSUE TITLE
Rhosimulator reloading on require.  

### ISSUE THREAD

**Issue by mbauer553** [rhomobile/rhodes#456]
In rhosimulator, every time a file is required, I believe it is reloaded.  I originally assumed this was intended as a feature so that you could edit your code live, and see the changes,  but per a discussion with Jon Tara, he recommended I submit an issue.  Our discussion can be found here: https://developer.motorolasolutions.com/thread/29908.  

Below is the support for my thinking on the requiring of files.  
# Simple test class

![test_class_screen](https://cloud.githubusercontent.com/assets/10281003/5684041/a757ead2-97f2-11e4-940f-992c4316e7fd.jpg)
# Controller usage

![controller_screen](https://cloud.githubusercontent.com/assets/10281003/5684059/b96083b0-97f2-11e4-9728-abad2c6bafb4.jpg)

Given the above code, I am expecting to see 'test' for @test_var the first time, and 'Test round 2' upon refresh.  This however is not the case in rhosimulator.  The value for @test_var is 'test' every time.  When performed outside of rhosimulator I receive the results I expect. 
# Rhosimulator test

![test_rhosim](https://cloud.githubusercontent.com/assets/10281003/5684070/cdca03ee-97f2-11e4-9493-187bccda4243.jpg)
# Win32 test

![test_win32](https://cloud.githubusercontent.com/assets/10281003/5684078/de257214-97f2-11e4-80fa-4d76ecec1028.jpg)

The work around we have been using is to require anything with a class variable in application.rb, which eliminates the issue, but it would be nice if we could require in the files that are going to utilize the classes. 

Thanks,

MAB

**Comment by hramovnik** [comment]
Currently, this is not bug. Controllers are use to be created every time with clean memory. 
The right way of using variables - is to save them in database.
