### ISSUE TITLE
barcode camera inverted rhomobile 4.1.1

### ISSUE THREAD

**Issue by gabyawad** [rhomobile/rhodes#492]
barcode camera inverted on android devices i am using rhomobile 4.1.1 
![20150206_180808](https://cloud.githubusercontent.com/assets/10921788/6105284/2fb08fb4-b05e-11e4-9650-67944be58b9d.jpg)
![20150206_180829](https://cloud.githubusercontent.com/assets/10921788/6105285/2fb53460-b05e-11e4-95a9-1f1f99d6b699.jpg)
![20150206_180916](https://cloud.githubusercontent.com/assets/10921788/6105286/2fb7bd70-b05e-11e4-8293-f3dccd8de654.jpg)

**Comment by alex-epifanoff** [comment]
@gabyawad Please use latest RMS versions provided by Tau:
http://tau-technologies.com/developers/downloads/
