### ISSUE TITLE
Need to .gitignore project directory in generated project

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#494]
The `.gitignore` file in the generated project (e.g. `rhodes app test`) needs to exclude the new `/project` directory to reflect new build file structure.

Otherwise, users will be checking-in compiled code unless they update `.gitignore` themselves.

**Comment by alex-epifanoff** [comment]
Not sure project/ should be ignored in all cases. As I understand some users may want to have generated xcode ( or other ) projects under source control ( if they make custom changes etc ). Would like to have a comment from @dmitrys .

**Comment by dmitrys** [comment]
Hm...
We discuss and make decision - most users do not want to save projects - so we add /project/ to gitignore by this commit:
https://github.com/rhomobile/rhodes/commit/3e90acebc92e673baf348dfa597e90dee10ea2fd
