### ISSUE TITLE
How install Rhodes gem - version 5.0.3

### ISSUE THREAD

**Issue by stopanko** [rhomobile/rhodes#549]
How i can install rhodes 5.0.3 instead default rubygems 3.5 version? LinuxMint
Maby how build 5.0.3 gem from github sourse and then install it

**Comment by ThierryW** [comment]
The only way I found is to download the 5.0.30 Rhodes version (https://developer.motorolasolutions.com/community/rhomobile-suite/rhomobile-community/rhomobile-blogs/blog/2015/03/03/rhomobile-suite-50-service-pack-2-5030-now-available). All necessary gems files are "hidden" in a .gems directory.

**Comment by darryncampbell** [comment]
Hi, I can confirm that is also the only officially supported method.

**Comment by stopanko** [comment]
rake build:android:rhobundle  
    exception: cannot load such file -- rhoconnect-client
    rake aborted!
    Can't find extension 'rhoconnect-client'. Aborting build.
    Extensions search paths are:

**Comment by darryncampbell** [comment]
rhoconnect-client is a separate gem and should also be part of the downloaded package (at the same location as the rhodes gem)

**Comment by stopanko** [comment]
How run emulator on linux_mintX32
`rake run:android`
`CMD: "/home/stopanko/android-sdk-linux/tools/emulator" -cpu-delay 0 -avd rhoAndroid422
ERROR: 32-bit Linux Android emulator binaries are DEPRECATED, to use them
       you will have to do at least one of the following:

       - Use the '-force-32bit' option when invoking 'emulator'.
       - Set ANDROID_EMULATOR_FORCE_32BIT to 'true' in your environment.`
