### ISSUE TITLE
Error in RhoConfig documentation

### ISSUE THREAD

**Issue by ThierryW** [rhomobile/rhodes#579]
At http://docs.rhomobile.com/en/5.0.30/guide/runtime_config, 
# application-specific value

foo = 'bar'
All values will be accessible at runtime via Rho::RhoConfig

foo = Rho::RhoConfig.bar                              # => should be "foo = Rho::RhoConfig.foo"
start_path = Rho::RhoConfig.start_path

**Comment by vmusulainen** [comment]
Fixed all version docs
