### ISSUE TITLE
Rho::Intent : cannot pass URI parameter

### ISSUE THREAD

**Issue by louisatome** [rhomobile/rhodes#599]
For the ACTION_VIDEO_CAPTURE android Intent, we should be able to pass an URI parameter as output result of the capture. But if i try to do that : 

``` ruby
intent_params = {     
        :action=> "android.media.action.VIDEO_CAPTURE",  
        :intentType => Rho::Intent::START_ACTIVITY,  
        :data => {:output =>"file:////example/of/file/path.mp4"} 
     }  
Rho::Intent.send(intent_params) 
```

My output param is ignored. After a deeper analysis i've found [this class](https://github.com/rhomobile/rhodes/blob/master/lib/commonAPI/coreapi/ext/platform/android/src/com/rho/intent/IntentSingleton.java#L165) and it seems that when the method parse the "extras" parameters, my output param is passed as a **String** while the android Intent needs an **Uri** object.

**Comment by hramovnik** [comment]
We fix this problem in this commit: https://github.com/rhomobile/rhodes/commit/103984c65fd8d6f5a41da84113027916f6f73478
