### ISSUE TITLE
System.screenHeight/Width incorrect on Android

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#698]
System.screenHeight/Width returns same value as System.realScreenHeight/Width on Android. 

They should return CSS width/height, i.e. divided by device pixel ratio.

It is correct for iOS.

This bug has been around for some time, previously reported on forum.

**Comment by jtara** [comment]
This issue has gone from bad to worse, or else my original observation was flawed.

With further observation, System.screenHeight/screenWidth and System.realScreenHeight/System.realScreenWidth are REVERSED.

Example: Galaxy S8

screenHeight: 2768
screenWidth:1440

realScreenHeight: 692
realScreenWidth: 360

ppix: 640
ppiy:640

It should be:

screenHeight: 692
screenWidth: 360

realScreenHeight: 2768
realScreenWidth: 1440

This is confirmed on Galaxy S8 (GenyMotion) and Galaxy Tab S2 9.1 (real)

It might be older versions reported both the same, but now they do report different, but wrong.

This was with master-pre-6-0 branch, commit c9eb3b4

**Comment by jtara** [comment]
I think there are implications beyond just getting wrong values from System. I am guessing this is used internally when creating the webview, and really goofs things up. I am getting VERY tiny font on Android.

**Comment by dmitrys** [comment]
Fixed by this commit: https://github.com/rhomobile/rhodes/commit/5b01905ec997474448a73602db617b95c46b886b

**Comment by jtara** [comment]
Could you also perhaps merge into master-pre-6-0?

I have merged into my own copy, so no hurry. Just might be good for others.
