### ISSUE TITLE
Android: Picture rotated by 90 degrees on Samsung phones

### ISSUE THREAD

**Issue by nhinze** [rhomobile/rhodes#811]
On Android, the saved picture using the new camera API with Rhodes 5.4 is rotated by 90 degrees with Samsung phones (S3, S5, ...). On Motorola phones the pictures are correctly rotated. This issue is not present when using the old camera API with Rhodes 5.0.25 .

**Comment by rognar** [comment]
Hi,

Please Sign-Up(using your developer e-mail) at tautechnologies.zendesk.com. After that you will be able to create tickets.

Regards,
Konstantin

**Comment by weiguangshi** [comment]
Not sure if this issue has been resolved? but I'm using Rho 5.5 and having the same issue...

**Comment by dmitrys** [comment]
Show your code for capture image

**Comment by nhinze** [comment]
This is resolved if you use these settings:

```
      cameraSettings['useSystemViewfinder'] = true
      cameraSettings['useRealBitmapResize'] = true
      cameraSettings['useRotationBitmapByEXIF'] = true
```
