### ISSUE TITLE
iOS: RhoContact.find can crash app

### ISSUE THREAD

**Issue by robroberts** [rhomobile/rhodes#812]
Calling RhoContact.find can crash the depending on the data in the phone's contacts. Here are two examples of it  happening, from different locations in the code:

Exception Type: EXC_BAD_ACCESS (SIGABRT)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Triggered by Thread: 8

Thread 8 Crashed:
0 libsystem_kernel.dylib 0x00000001817c811c __pthread_kill + 8
1 libsystem_pthread.dylib 0x0000000181894ef8 pthread_kill + 112
2 libsystem_c.dylib 0x0000000181739dac abort + 140
3 rhorunner 0x00000001003c5acc report_bug (error.c:227)
4 rhorunner 0x000000010042ea78 sigpipe (signal.c:621)
5 libsystem_platform.dylib 0x000000018188d94c _sigtramp + 68
6 rhorunner 0x00000001002ae604 _getRecord (phonebook.m:182)
7 rhorunner 0x00000001002ae604 _getRecord (phonebook.m:182)
8 rhorunner 0x00000001002adfb0 getPhonebookRecords (phonebook.m:489)
9 rhorunner 0x0000000100491440 _wrap_getRecords (phonebook_wrap.c:2087)
10 rhorunner 0x000000010047c1b4 vm_call_cfunc (vm_insnhelper.c:402)
11 rhorunner 0x000000010047b398 vm_call_method (vm_insnhelper.c:524)
12 rhorunner 0x0000000100471fb4 vm_exec_core (insns.def:1006)
13 rhorunner 0x0000000100477074 vm_exec (vm.c:1155)
14 rhorunner 0x0000000100476050 vm_call0 (vm_eval.c:68)
15 rhorunner 0x00000001004755c4 rb_funcall (vm_eval.c:640)
16 rhorunner 0x0000000100493bac callFramework (rhoruby.c:1039)
17 rhorunner 0x00000001002de210 rho::net::CHttpServer::decide(std::string const&, std::string const&, std::string const&, rho::Vector<rho::net::HttpHeader> const&, std::string const&) (HttpServer.cpp:1418)
18 rhorunner 0x00000001002dc5dc rho::net::CHttpServer::process(int) (HttpServer.cpp:885)
19 rhorunner 0x00000001002dc2dc rho::net::CHttpServer::run() (HttpServer.cpp:572)
20 rhorunner 0x000000010037e774 rho::common::CRhodesApp::run() (RhodesApp.cpp:556)
21 rhorunner 0x00000001002d1834 rho::common::CRhoThread::runObject() (RhoThread.h:62)
22 rhorunner 0x00000001002dac5c rho::common::runProc(void*) (PosixThreadImpl.cpp:66)
23 libsystem_pthread.dylib 0x0000000181893b28 _pthread_body + 156
24 libsystem_pthread.dylib 0x0000000181893a8c _pthread_body + 0
25 libsystem_pthread.dylib 0x0000000181891028 thread_start + 4

Exception Type:  EXC_BAD_ACCESS (SIGABRT)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Triggered by Thread:  9

Thread 9 Crashed:
0   libsystem_kernel.dylib            0x000000018162c11c __pthread_kill + 8
1   libsystem_pthread.dylib           0x00000001816f8ef8 pthread_kill + 112
2   libsystem_c.dylib                 0x000000018159ddac abort + 140
3   rhorunner                         0x000000010036dacc report_bug (error.c:227)
4   rhorunner                         0x00000001003d6a78 sigpipe (signal.c:621)
5   libsystem_platform.dylib          0x00000001816f194c _sigtramp + 68
6   rhorunner                         0x0000000100256960 _getRecord (phonebook.m:241)
7   rhorunner                         0x0000000100256960 _getRecord (phonebook.m:241)
8   rhorunner                         0x0000000100256210 getPhonebookRecords (phonebook.m:491)
9   rhorunner                         0x0000000100439440 _wrap_getRecords (phonebook_wrap.c:2087)
10  rhorunner                         0x00000001004241b4 vm_call_cfunc (vm_insnhelper.c:402)
11  rhorunner                         0x0000000100423398 vm_call_method (vm_insnhelper.c:524)
12  rhorunner                         0x0000000100419fb4 vm_exec_core (insns.def:1006)
13  rhorunner                         0x000000010041f074 vm_exec (vm.c:1155)
14  rhorunner                         0x000000010041e050 vm_call0 (vm_eval.c:68)
15  rhorunner                         0x000000010041d5c4 rb_funcall (vm_eval.c:640)
16  rhorunner                         0x000000010043bbac callFramework (rhoruby.c:1039)
17  rhorunner                         0x0000000100286210 rho::net::CHttpServer::decide(std::string const&, std::string const&, std::string const&, rho::Vector<rho::net::HttpHeader> const&, std::string const&) (HttpServer.cpp:1418)
18  rhorunner                         0x00000001002845dc rho::net::CHttpServer::process(int) (HttpServer.cpp:885)
19  rhorunner                         0x00000001002842dc rho::net::CHttpServer::run() (HttpServer.cpp:572)
20  rhorunner                         0x0000000100326774 rho::common::CRhodesApp::run() (RhodesApp.cpp:556)
21  rhorunner                         0x0000000100279834 rho::common::CRhoThread::runObject() (RhoThread.h:62)
22  rhorunner                         0x0000000100282c5c rho::common::runProc(void*) (PosixThreadImpl.cpp:66)
23  libsystem_pthread.dylib           0x00000001816f7b28 _pthread_body + 156
24  libsystem_pthread.dylib           0x00000001816f7a8c _pthread_body + 0
25  libsystem_pthread.dylib           0x00000001816f5028 thread_start + 4

**Comment by robroberts** [comment]
I've committed a fix for this in commit 21f7d679, which is in this pull request: https://github.com/rhomobile/rhodes/pull/813

**Comment by dmitrys** [comment]
Thank you for your participation !
