### ISSUE TITLE
ERROR ITMS-90475 when submitting app to itunes

### ISSUE THREAD

**Issue by charlyR** [rhomobile/rhodes#818]
ERROR ITMS-90475: "Invalid Bundle. iPad Multitasking support requires launch storyboard in bundle 'com.companyname.appname.'"
Manually fixed by adding the key to info.plist
```
<key>UIRequiresFullScreen</key>
<true/>
```
Add an option to support or not iPad mutitasking in build.yml

**Comment by dmitrys** [comment]
Hi,
Thank you for cooperation.
We known this issue.
Now we preparing new 5.5 release with full support latest iOS requirements and iOS 10 support.
For Rhodes based application this key should be always defined in .plist file by technilcal reason.
We prepare new sources in branch.
You can see this change in this commit: https://github.com/rhomobile/rhodes/commit/e39f7f88c6dc3ecafb0d149c17f7e0189d43063c
