### ISSUE TITLE
Unable to create APK for Android with RhoElements 

### ISSUE THREAD

**Issue by weiguangshi** [rhomobile/rhodes#825]
Migrate a RhoElement app from Rho 5.4 to Rho 5.5. However, receiving error when compiling.

 No Android SDK add-on found: EMDK

Tasks: TOP => build:android:extensions => config:android:extensions
(See full trace by running task with --trace)
extjsmodulefiles=["C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/jquery-2.0.2-rho-custom.min.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/rhoapi.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Application.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Config.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Database.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Database.SQLite3.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Intent.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Log.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.NativeMenubar.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.NativeTabbar.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.NativeToolbar.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Navbar.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Network.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.NewORM.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.NewORMModel.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Notification.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Push.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.RhoFile.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.System.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.System.Process.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.Timer.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/generated/Rho.WebView.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/mediacapture/public/api/generated/Rho.Camera.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/mediacapture/public/api/generated/Rho.Videocapture.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/symboldevice/public/api/generated/Rho.Device.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/symboldevice/public/api/generated/Rho.DeviceMemory.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/barcode/public/api/generated/Rho.Barcode.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/signature/public/api/generated/Rho.Signature.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/indicators/public/api/generated/Rho.Battery.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/indicators/public/api/generated/Rho.KeyState.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/indicators/public/api/generated/Rho.SignalIndicators.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/hardwarekeys/public/api/generated/Rho.KeyCapture.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/sensor/public/api/generated/Rho.Sensor.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/Rho.Application.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/Rho.Database.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/Rho.NewORMHelper.js"]
!!!MODIFY C:/Users/wshi/workspace_5/Checkout/bin/tmp/assets/apps/public/api/rhoapi-modules.js
extjsmodulefiles_opt=["C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/Rho.ORM.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/Rho.ORMHelper.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/Rho.Rhosim.Fix.js", "C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/public/api/Rho.Ruby.RunTime.js"]
!!!MODIFY C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/platform/shared/ruby/ext/rho/extensions.c
-$TIME$- message [ init_extensions() FINISH ] time is { 2016-09-28T13:54:49Z } milliseconds from start (2183)
-$TIME$- message [ common_bundle_start() FINISH ] time is { 2016-09-28T13:54:50Z } milliseconds from start (2709)
Running default.rb

Running compileRB

-$TIME$- message [ android:extensions START ] time is { 2016-09-28T13:54:51Z } milliseconds from start (3810)
C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi is configuring...
C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/ext.yml is processing...
-$TIME$- message [  extension "coreapi" processing START ] time is { 2016-09-28T13:54:51Z } milliseconds from start (3810)
C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi/ext.yml is processed
-$TIME$- message [  extension "coreapi" processing FINISH ] time is { 2016-09-28T13:54:51Z } milliseconds from start (3812)
C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/lib/commonAPI/coreapi is configured
C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/extensions/emdk3-manager is configuring...
C:/RhoMobileSuite5.5.0/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.0/extensions/emdk3-manager/ext.yml is processing...
-$TIME$- message [  extension "emdk3-manager" processing START ] time is { 2016-09-28T13:54:51Z } milliseconds from start (3849)
**** WARNING *************************************************************************************************
   The following extensions do not have JavaScript API: 
   rhoelementsext
   Use RMS 4.0 extensions to provide JavaScript API
**************************************************************************************************************
RET: 1

**Comment by dmitrys** [comment]
This issue described in ReleaseNotes of Rhodes 5.5
You should download and install EMDK - https://portal.motorolasolutions.com/Support/US-EN/Resolution?solutionId=102252&productDetailGUID=f5563b1ca4151410VgnVCM10000001c7b00aRCRD&detailChannelGUID=a0bde8cea8151410VgnVCM10000001c7b00aRCRD
This addon for Android contain libraries for access to Barcode functionality and other features of Zebra devices. Barcode extension support not only S/W recogrnition on iOS and consumer Android devices but also HW Barcode scaners on Zebra devices and require EMDK for building.
