### ISSUE TITLE
Unable to complete production build for iPhone

### ISSUE THREAD

**Issue by gitrepo4koresol** [rhomobile/rhodes#830]
Hi
We have successfully setup the Rhostudio 5.5.0.2 on OSx 10.12 and using Xcode 8.
We are able to run application within "Rhosimulator"  successfully.
But when we try to start "production build" or try to run "Simulator" configuration then it throws below error:
 
_________________________________________________________
Running default.rb
RubyMac(1775,0xa50c11c0) malloc: *** error for object 0x802400: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

Error interpreting erb code
RET: 1

__________________________________________________________

Please also find attached complete log of Rhostudio, generated during  running the project.
Please could you suggest where we are going wrong, and help us to solve this issue ..

Thank You for your help!!
[rhostudionConsoleLog.txt](https://github.com/rhomobile/rhodes/files/526741/rhostudionConsoleLog.txt)

**Comment by dmitrys** [comment]
Issue looks like OSx 10.12 related
We work with it now - fix will provided soon
If you has some issues you can add it to our Zendesk :
https://tautechnologies.zendesk.com


TAU Technologies

**Comment by rognar** [comment]
Hello gitrepo4koresol,
We are working on that issue. As Dmitry mentioned before this is Sierra related issue.
Please sign-up at  https://tautechnologies.zendesk.com and file a ticket.

Regards,
Konstantin

**Comment by gitrepo4koresol** [comment]
Hello Konstantin and Dmitry
We appreciate your help and thank you for quick reply ..
As suggested, opening the ticket right now ...

KORESOL

**Comment by vmusulainen** [comment]
Some observations: 
Sometimes RubyMac launching has been hung.
If so (sometimes too) compiling process may complete successful.
And it is no a chance on success if not such hanged process in memory.

**Comment by gitrepo4koresol** [comment]
Hi - Thank you for sharing the observations .. 
Would you like us to try any specific approach or test it in other way, please let us know - we will do it and let you know the test results ..

**Comment by rognar** [comment]
Hi. 
The issue has been solved by this commit https://github.com/rhomobile/rhodes/commit/35a0e37ea790b22465b9d8b3c46d9936b3ca7ef0

But we are still in a test process. Rho 5.5.0.3 will be built by Monday.

Regards,
Konstantin

**Comment by gitrepo4koresol** [comment]
Hi Konstantin
That's fabulous ... You and team are super-fast ..
We are thankful for all the efforts you poured to build such a fabulous platform. and providing such a superb support ....
Waiting  to try Rho 5.5.0.3  ...

Best Regards,
Nitin

**Comment by rognar** [comment]
Hi Nitin,

5.5.0.3 is available for download at http://rhomobile.tau-technologies.com/index.html

Regards,
Konstantin

**Comment by gitrepo4koresol** [comment]
Hello Konstantin 

We downloaded the Rho 5.5.0.3 and successfully created "production build (.ipa file)" as well as successfully ran "simulator" on OSx 10.12 (Sierra).
You guys rock .. :) ..
Thank You, Thank you very much for such a superb and prompt help.

Best Regards, 
Nitin
