### ISSUE TITLE
5.5 : Cannot create TCPServer within a Thread with iOS

### ISSUE THREAD

**Issue by louisatome** [rhomobile/rhodes#831]
If i try to create a TCPServer within a Thread with rhodes 5.5, i cannot accept connection from clients.
Example : 

```ruby
thread = Thread.new {
      tcp_server = TCPServer.open(1211)
      loop {
        client = tcp_server.accept
        client.puts(Time.now.ctime)
        client.puts "Closing the connection. Bye!"
        client.close
      }
}
```

It used to work with rhodes 5.4. If i try without a thread, everything works well. This problem doesn't occur on android devices.

**Comment by rognar** [comment]
Please create a ticket at https://tautechnologies.zendesk.com

**Comment by rognar** [comment]
Fixed by commit below 
https://github.com/rhomobile/rhodes/commit/ca03ad7635038171ad1b67eed19ab228c7dae17d

**Comment by louisatome** [comment]
Thanks for the quick fix! It works perfectly!
