### ISSUE TITLE
Error using openssl-edge

### ISSUE THREAD

**Issue by louisatome** [rhomobile/rhodes#834]
I try to use the new openssl-edge from tau-extensions that brings OpenSSL 1.1.0 but i have an error when i try to use SSL Sockets :

``` ruby
ssl_context = OpenSSL::SSL::SSLContext.new()
ssl_context.cert = OpenSSL::X509::Certificate.new($cert)
ssl_context.key = OpenSSL::PKey::RSA.new($key, Constants::KEY_PASSWORD)
# ssl_context.ssl_version = :SSLv3
ssl_context.ssl_timeout = Constants::SSL_TIMEOUT

ssl_socket = OpenSSL::SSL::SSLSocket.new(socket, ssl_context)
# ssl_socket.sync_close = true

ssl_socket.connect_nonblock()
```

The error i get is on the `connect_nonblock()` method:
`fatal: bad scan arg format: 0`

Furthermore, i have error on the commented lines:
`# ssl_context.ssl_version = :SSLv3`
and
`# ssl_socket.sync_close = true`
that say these methods doesn't exist.

It used to work with the older openssl extension.

**Comment by rognar** [comment]
We are working on this issue.

Regards,
Konstantin

**Comment by alex-epifanoff** [comment]
Probably we have some incompatibilities with outdated Ruby VM.
As now RhoMobile is in the process of migrating to Ruby 2.3, OpenSSL issue will be investigated, and probably resolved in the context of this upgrade.

**Comment by alex-epifanoff** [comment]
@louisatome openssl-edge is now updated to 1.1.0h. 'openssl' is updated to 1.1.0h as well in recent RMS 6.x builds.

**Comment by louisatome** [comment]
The new openssl version shipped with the rhodes core works well. This issue is no longer relevant.
