### ISSUE TITLE
Native Toolbar not rendered properly

### ISSUE THREAD

**Issue by jacobrails** [rhomobile/rhodes#855]
Hi
We have successfully setup the RMS 5.4.0 on on windows server.
We can see, below sdk version in build.yml:

*******************************************  
#sdk: "C:/RhoMobileSuite5.5.14/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.5.14"
sdkversion: "5.5.0"
******************************************   

We successfully ran application within "Rhosimulator". Native toolbar (at the bottom of screen) looked OK in Rhosimulator.
But when we installed the generated APK on mobile, there was dark patch on each Native Toolbar Icon (at the bottom of screen). Also, background color of toolbar not getting applied at first load.

Please guide us to solve this problem ..
Thank You for your help!!

![rhomobile toolbar problem](https://cloud.githubusercontent.com/assets/26685245/24329496/4ddb056a-1226-11e7-864a-bd0fee57736e.jpg)

**Comment by vmusulainen** [comment]
Hi, could you provide code that create Native toolbar ?

**Comment by jacobrails** [comment]
Hi - Please find below the code to create Native Toolbar

**************************
toolbar = [
                        {:label => 'Back',:action => :back,    
                        :icon => '/public/images/back.png'},
        {:action => :separator},  
            
                        {:label => 'Home', :action => 'https://mycan.in/mobilehome',
                          :icon => '/public/images/home.png'},
        {:action => :separator},
                        {:label => 'Refresh',:action => :refresh,
                          :icon => '/public/images/refresh.png'},
        {:action => :separator},
                        {:label => 'Cart',:action => 'https://mycan.in/cart',
                          :icon => '/public/images/cart.png'}
                        
                      ]
                      
      Rho::NativeToolbar.create(toolbar, :background_color => 0x0096de,:view_height => 50)


**************************

**Comment by vmusulainen** [comment]
I confirm the issue.
Note: please use camel style in parameter's names: "backgroundColor" instead "background_color". 
The CommonApi still supports old style but it is deprecated.

**Comment by jacobrails** [comment]
Superb .. Yes- it works .. Thank you very much for your help ...
Also need quick help . When I create APK - debuggable APK gets created ..
Please could you let me know the setting, where I can turn off debuggagle flag, and APK will be production ready ..

For your information- When I upload generated APK on Google Play Store, I receive below error:
++++++++++++++++++++++++++++++++ 
You uploaded a debuggable APK. For security reasons you need to disable debugging before it can be published in Google Play.
+++++++++++++++++++++++++++++++

**Comment by jacobrails** [comment]
I could see below line - within "AndroidManifest.erb" ..
android:debuggable='<%= @debuggable %>'>

But - not sure, if is this line we need to modify, or what value to set against this parameter or some other settings are required ..
We did not face this problem with old versions of RMS (5.0.25) ..
Please help!!

**Comment by vmusulainen** [comment]
Do you change a value of the "build" setting in build.yml ?

```
build	Build configuration of this version of your app.	Debug
												development
												release
```

http://docs.rhomobile.com/en/5.4/guide/build_config#other-build-time-settings

**Comment by jacobrails** [comment]
Yeah .. right .. Thank you for sharing the link .. all is well now ... :)
