### ISSUE TITLE
Not able to download latest version of Rhomobile suite.

### ISSUE THREAD

**Issue by VivekSharma02** [rhomobile/rhodes#862]
I am trying to download latest version of Rhomobile (5.4) suite, after signing onto rhomobile account i am redirected to a page where i cannot see any link to download. 
![image](https://cloud.githubusercontent.com/assets/26112669/24835402/0ce82f84-1d1f-11e7-9ffa-3e5466c32b6d.png)
 
Tried using it other id, but after signing up from google account, in the end it shows blank screen with invalid_credentials written over it.

**Comment by dmitrys** [comment]
Now Rhomobile Suite developed and support by Tau Technologies(http://tau-technologies.com/).
See FAQ from Zebra - https://developer.zebra.com/community/rhomobile-suite/rhomobile-community/rhomobile-blogs/blog/2016/03/30/rhomobile-open-source-faq
You can download current RMS versions from this: http://rhomobile.tau-technologies.com/index.html
Latest release is 5.5 (September 2016). 6.0 is coming June 2017 and will contain some major changes/new features (like new Ruby VM, Node.js environment on mobile device etc.).
5.5.X - current version with new features - for developers
5.5.0.X - stable versions based on 5.5 release and contain only important bugfixes
Bugtracker: https://tautechnologies.zendesk.com
Forum: http://forums.tau-technologies.com/
