### ISSUE TITLE
iOS simulators do not scale

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#865]
Rhomobile iOS simulators (Apple simulator, not RhoSimulator) do not scale. Change to 75%, 50% etc and it does nothing. It's quite inconvenient debugging iPad.

It appears the iOS simulator interface had to change yet again, so I guess a bug or oversight.

I can scale iPad when I build a (non-Rhomobile) pure native app.

This is on recent master, 5.5.1.8  
commit info:
`2fff85e085bf4e186cf40ecc0cc03cf772a2be32`
2fff85e0 Merge pull request #864 from rhomobile/WinMobile

I am slightly back from current XCode, I am using 8.2.1

I checked both iPad and iPhone simulators, both have same problem.

**Comment by jtara** [comment]
Sorry, now I think it has nothing to do with Rhodes. Now I can't scale the other pure native app either. Maybe is issue with XCode. But will leave this open until more investigation, I will try resetting simulator and then try latest XCode.

**Comment by jtara** [comment]
Yes, something strange going on. I just scaled an empty simulator instance successfully.

**Comment by alex-epifanoff** [comment]
Jon is there any issue now? I don't think Rhodes app can change simulator behavior somehow.

**Comment by jtara** [comment]
With XCode 8, Rhodes creates it's own simulator instances. They are not the simulators that come with XCode.  They are named like "Rhomobile iPhone 7 10.2". They don't seem to respond to the scaling settings on the ios simulator menu.

**Comment by jtara** [comment]
This seems solves in XCode 9.

iPad simulator now comes up at a more reasonable size by default. And, as well I can now resize the simulator with Window Scale.
