### ISSUE TITLE
In a rhoelements app, NFCManager is not found(const_missing)

### ISSUE THREAD

**Issue by jameslh** [rhomobile/rhodes#876]
When using version 5.5.19 in a rhoelements app, NFCManager is not found (const_missing).
I have the EMDK installed if that matters. Is NFC still expected to work in this scenario?

~~~~
def on_activate_app
  p "ENABLED " + Rho::NFCManager.is_enabled.to_s
end
~~~~

~~~~
sdkversion: "5.5.19"
name: "ntest"
version: 1.0
vendor: "ntest"
app_type: "rhoelements"
rho_app_id: "com.rhomobile.ntest"
build: "debug"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "latest"
  BundleIdentifier: "com.rhomobile.ntest"
capabilities:
  - audio
  - camera
  - gps
  - network_state
  - sdcard
  - motorola_browser
wp8:
  productid: "e7db4cf1-2763-0135-5198-00ff71d41a84"
android:
  version: "4.4.2"
  logcatFilter: "APP:I StrictMode:I DEBUG:I *:E"
  extensions:
    - nfc
  capabilities:
    - sdcard
    - hardware_acceleration
    - non_motorola_device
wm:
  extensions:
    - webkit
win32:
  deployqt: 1
  deploymsvc: 1
extensions:
  - rhoconnect-client
  - rho-javascript
  - json
rhobundle:
  exclude_items:
    - thumb.db
~~~~

**Comment by dmitrys** [comment]
nfc extensions is old-style only-ruby extension.
So you should add "require 'nfc'" to start of your controller code.
See complete example : https://github.com/tauplatform/rhodes-system-api-samples/tree/master/app/Nfc

**Comment by jameslh** [comment]
Thanks for the response - I had require 'nfc' in my application.rb but I still got the error. I don't have time to investigate further, but I got around the issue by modifying IntentSingleton.java in the framework which is not ideal, but it will work.
