### ISSUE TITLE
Webview (external URL) problem while running app on iPhone using Xcode

### ISSUE THREAD

**Issue by jacobrails** [rhomobile/rhodes#879]
Hi 
We are facing Webview problem while running app on iPhone using Xcode.
Blank white screen shows up after running app on iPhone using Xcode.
We noted the debug log generated within Xcode for "HTTP" and "HTTPS" protocols.
Please find below these logs and other configuration details below.
+++++++++++++++++++++++++++++++++++++++++++++++++++++
1> Xcode Version: 8.3.3
2> SDK version:   iphoneos10.3 (within build.yml)
3> RMS for Mac: RMS_5.5.0.29
4> iPhone OS:  10.3.2
5> WIthin "rhoconfig.txt", tried  URLs below:
    For first test - HTTPS:      start_path = 'https://mycan.in/mobilehome'
    For second test - HTTP:      start_path = 'http://mycan.in/mobilehome'

6> HTTPS:   Error log while trying to load external URL (https://mycan.in/mobilehome) : 
     
     Within Rhosimulator received Error : "SSL handshake failed"

     For  Xcode debug log, please refer attached file **"https-error.txt"**

7> HTTP:   Error log while trying to load external URL (http://mycan.in/mobilehome) : 
     
     Within Rhosimulator,  HTTP protocol URL worked perfect

     For  Xcode debug log please refer attached file **"http-error.txt"**

+++++++++++++++++++++++++++++++++++++++++++++++++++++

Please help us solve this webview problem.

[https-error.txt](https://github.com/rhomobile/rhodes/files/1085130/https-error.txt)
[http-error.txt](https://github.com/rhomobile/rhodes/files/1085131/http-error.txt)

**Comment by jacobrails** [comment]
Hello - 
I reinstalled RMS and installed set of related GEMS again ..
Recreated project within Xcode, and now I am able to run HTTP and HTTPS, both type of URLs on iPhone using Xcode ...
Sorry for the trouble caused ...

However - for HTTPS - within Rhosimulator still receiving Error : "SSL handshake failed" ..
But it is not affecting us .. This is just for your information .. Thank You for supporting such a strong platform for mobile app development !!

**Comment by alex-epifanoff** [comment]
@jacobrails FYI RMS 6.0 was released.
