### ISSUE TITLE
Android: browser uses real device pixels if targetSDKVersion >= 19

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#890]
If AndroidManifest targetSDKVersion >= 19, then real device pixels are used, rather than CSS pixels.

This breaks most CSS and Javascript frameworks/libraries dealing with UI, as they are expecting CSS pixels. Most obvious symptom is very tiny text and other UI elements.

If targetSDKVersion < 19, Chrome-based WebView (KitKat or newer) will be set in "quirks mode".

Prior to KitKat, Android WebView always used 1:1 real device pixels. I believe Rhodes did some work-around for that, and likely this failure is due to the work-around not being appropriate unless quirks mode is used.

See:

 developer.android.com/guide/webapps/migrating.html

And thread on forum:

http://forums.tau-technologies.com/thread/67/android-targetsdkversion-hard-coded-androidmanifest

**Comment by jtara** [comment]
Related:

https://github.com/rhomobile/rhodes/issues/698

**Comment by hramovnik** [comment]
I hope we have fixed this issue by this commit: https://github.com/rhomobile/rhodes/commit/c97d8013072de354b2141c544ae1e4c011015925

**Comment by jtara** [comment]
Works for me. I'm now using target sdk 25. No tiny text!
