### ISSUE TITLE
iOS dyld: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by lothcor** [rhomobile/rhodes#891]
When building using 

OSX 10.12.6
XCode 8.3.3
Ruby 2.3.4 (or 1.9.3)
and Master branch of rhodes

I have been able to replicate this on iOS simulators as well as actual devices.
Build through XCode or command line, doesn't matter which, it seems to be an issue with iOS versions < 10

iPhone4s device iOS 9.3 fails
iPhone 7 device running 10.2 works

iPhone6s Simulator running iOS 9.3 fails 
iPhone7Plus simulator running 10.2/10.3 works

Jul 26 12:17:16 Davids-iPhone rhorunner[583] <Notice>: dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
Referenced from: /var/containers/Bundle/Application/CFAB70B1-A557-4CBA-89A6-4B91AB32D24A/HerdData.app/rhorunner
Expected in: dyld shared cache
Jul 26 12:17:16 Davids-iPhone rhorunner[583] <Notice>: dyld: Symbol not found: _clock_gettime
Referenced from: /var/containers/Bundle/Application/CFAB70B1-A557-4CBA-89A6-4B91AB32D24A/HerdData.app/rhorunner
Expected in: dyld shared cache
Jul 26 12:17:16 Davids-iPhone com.apple.xpc.launchd[1] (UIKitApplication:au.com.datagene.herddataapp[0xdc79][583]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
Jul 26 12:17:17 Davids-iPhone SpringBoard[48] <Warning>: Application 'UIKitApplication:au.com.datagene.herddataapp[0xdc79]' crashed.
Jul 26 12:17:17 Davids-iPhone UserEventAgent[23] <Warning>: 2535750755087: id=au.com.datagene.herddataapp pid=583, state=0

**Comment by jtara** [comment]
Confirm on iPad 3 with iOS 9.3.5

**Comment by dmitrys** [comment]
Alredy fixed - https://github.com/rhomobile/rhodes/commit/1ca4cd34a8be3df9f7ac0263f03e0e7d5de27b62#diff-f183d902581a7c969a7ff92db57dbafc

**Comment by dmitrys** [comment]
6.0 release(where this issue is fixed) is coming - will be published in few days
