### ISSUE TITLE
Incorrect ppi for iPhone X, iPhone plus models

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#920]
Incorrect ppi is being reported by `System.ppiX`, `System.ppiY` on iPhone X.

Reported value is 326. Should be 458.

As well, is it incorrect for iPhone 7+ (and I presume for 6+ and 6S+ - only tested on 7+). Correct PPI is 401 for plus models.

**Comment by jtara** [comment]
Noted I edited title a comment above to add iPhone plus models

**Comment by dmitrys** [comment]
fixed by this commit: https://github.com/rhomobile/rhodes/commit/5873835cdf8a25577e713ed17c66e2beb1750759
