### ISSUE TITLE
render :partial and subfolders

### ISSUE THREAD

**Issue by danielbsig** [rhomobile/rhodes#928]
Hi,

I have a RhoMobile application, and I want to use partials for certain parts of the application. Also, I would like to categorize the partials into subfolders. I.e. I will have folders/files as follows:

app/Common/Widget1/_widget1.erb
app/Common/Widget2/_widget2.erb

etc., i.e. each widget has its own folder since there may be other files accompanying each widget.

However, when I try to use render :partial, it seems that it will not accept the file path as is, but will only use the last part of the path. I.e. when I use the following in some .erb file:

<%= render :partial => "Common/Widget1/widget1", locals: {etc} %>

then I will get a runtime error, claiming that the system cannot find "app/Widget1/_widget1.erb".

Is there anything I can do to ensure my partials can be found?

N.b. I'm using RhoStudio 5.5.

Regards,
Daníel

**Comment by dmitrys** [comment]
It is impossible currently.
You can put your files in separated "model" folders (top folders in root /app folder).
Like this:

app/CommonWidget1/_widget1.erb
app/CommonWidget2/_widget2.erb

and use next render execute :

<%= render :partial => "CommonWidget1/widget1", locals: {etc} %>

**Comment by danielbsig** [comment]
I suspected this.

The reason why the workaround is not optimal in my case is that I have multiple clients with similar code, but not similar enough to use the exact same codebase. To tackel this, our plan is to have a "Common" folder directly beneath "/app", and ensure that all common/shared code will live there, while the rest of the application will live in regular Controller folders. We will then use the "subrepo" git plugin to ensure the Common folder stays in sync between all clients. Ideally, we would be able to group the files in the Common folder based on features, i.e. there would be a separate folder for code relating to data sync, another for code which interacts with the built-in barcode scanner, etc. 

I started with placing all the partials inside the root of the Common folder, and will probably continue with that approach unless some other solution pops up.

Thanks for the reply!

**Comment by danielbsig** [comment]
Just to clarify further: this folder issue: does it apply to all code, not just partials? I.e. is the build process not looking any deeper in the source tree than /app/somefolder/somefile.ext ?

**Comment by dmitrys** [comment]
This is specific issue for partials. All files located in subfolders etc. will be included into bundle. And you can open it in code or from local server. But partials processing has some limitations in code.

**Comment by danielbsig** [comment]
Ok thanks, and would it be necessary to wrap said objects in a module or a namespace?

**Comment by dmitrys** [comment]
If you place some ruby code in separated file, you should load it manually in ruby code. Ruby code from model and controller loaded automatically, but other code not.

**Comment by dmitrys** [comment]
and keep in mind - on device ruby code files not *.rb - ruby code compiled into bytecode *.iseq files.

**Comment by danielbsig** [comment]
Ok thanks, and what about routing? If I declare a controller in a subfolder, would I have to do anything specific to make routing to that controller work?

**Comment by dmitrys** [comment]
controller must be locate in /app/controllername/ folder
you can place other ruby files everywhere but should load them manually from ruby code of application.rb or any controller/model

**Comment by danielbsig** [comment]
Ah ok, is there no workaround for the controller placement?
