### ISSUE TITLE
Rho::Timer.start undocumented third parameter

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#939]
*Rho::Timer.start* required third parameter (when callback) is not documented. It is data to send to the callback.

http://docs.tau-technologies.com/en/6.0/api/Timer#Examples

**Comment by dmitrys** [comment]
It is legacy old only Ruby API and it is documented - http://docs.tau-technologies.com/en/2.2.0/rhodesapi/timer-api

In new API you can not just execute start() - you should make timer object previously and call instance method start() from timer object

This is Ruby code for support old API - https://github.com/rhomobile/rhodes/blob/master/lib/commonAPI/coreapi/RhoTimerApi.rb
This is original XML description of new Common API Timer - https://github.com/rhomobile/rhodes/blob/master/lib/commonAPI/coreapi/ext/Timer.xml
