### ISSUE TITLE
Can't build test app debug apk

### ISSUE THREAD

**Issue by arjunmenon** [rhomobile/rhodes#941]
Hey
My `bashrc` file in Elementary os 0.4.1/Ubuntu 16.04
```bash
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/ndk-bundle
```
I downloaded the NDK from the Android studio tool, which installed it inside the `ANDROID_HOME` folder above.

```ruby
>$ rhodes-setup
We will ask you a few questions below about your dev environment.

JDK path (required) (/usr/lib/jvm/java-8-oracle): /usr/lib/jvm/java-8-oracle
Android SDK path (blank to skip) (/home/arjun/Android/Sdk): /home/arjun/Android/Sdk
Android NDK path (blank to skip) (): /home/arjun/Android/Sdk/ndk-bundle
Windows Mobile 6 SDK CabWiz (blank to skip) (): 
BlackBerry JDE 4.6 (blank to skip) (): 
BlackBerry JDE 4.6 MDS (blank to skip) (): 
BlackBerry JDE 4.2 (blank to skip) (): 
BlackBerry JDE 4.2 MDS (blank to skip) (): 

If you want to build with other BlackBerry SDK versions edit: /home/arjun/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rhodes-6.0.11/rhobuild.yml

>$ rhodes app testapp
Generating with app generator:
     [ADDED]  testapp/rhoconfig.txt
     [ADDED]  testapp/build.yml
     [ADDED]  testapp/.gitignore
     [ADDED]  testapp/app/application.rb
     [ADDED]  testapp/app/index.erb
     [ADDED]  testapp/app/layout.erb
     [ADDED]  testapp/app/loading.html
     [ADDED]  testapp/app/Settings/controller.rb
     [ADDED]  testapp/app/Settings/err_sync.erb
     [ADDED]  testapp/app/Settings/home.erb
     [ADDED]  testapp/app/Settings/index.erb
     [ADDED]  testapp/app/Settings/login.erb
     [ADDED]  testapp/app/Settings/reset.erb
     [ADDED]  testapp/app/Settings/wait.erb
     [ADDED]  testapp/Rakefile
     [ADDED]  testapp/app/loading.png
     [ADDED]  testapp/AndroidManifest.erb
     [ADDED]  testapp/app/helpers
     [ADDED]  testapp/icon
     [ADDED]  testapp/resources
     [ADDED]  testapp/public
```

This is the log of running `rake:device:android:debug`
```bash
...
...
rake aborted!
Extension build failed: /home/arjun/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rhodes-6.0.11/lib/commonAPI/coreapi/ext/platform/android
```
Full log - https://paste.ubuntu.com/26321477/

---
EDIT
I also tried changing the default Android version in build.yml from 4.1.0 to 5.1 to 6.0
Nothing happened. Got the same error.
I have even tried all of these Target SDKs. None works.
```bash
>$ android list target
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Running /home/arjun/Android/Sdk/tools/bin/avdmanager list target

Available Android targets:==============] 100% Fetch remote repository...       
----------
id: 1 or "android-22"
     Name: Android API 22
     Type: Platform
     API level: 22
     Revision: 2
----------
id: 2 or "android-23"
     Name: Android API 23
     Type: Platform
     API level: 23
     Revision: 3
----------
id: 3 or "android-26"
     Name: Android API 26
     Type: Platform
     API level: 26
     Revision: 2
----------
id: 4 or "android-27"
     Name: Android API 27
     Type: Platform
     API level: 27
     Revision: 1
```

**Comment by alex-epifanoff** [comment]
Hello @arjunmenon 

1) Please run build command with --trace key, it should give more information
2) Make sure you are not using NDK v16, it is not supported yet, please see forum thread:
http://forums.tau-technologies.com/thread/105/ndk16-supported-rhodes

**Comment by arjunmenon** [comment]
Hey
1. This is the full trace - https://paste.ubuntu.com/26324402/
2. Okay. I will download 15c. I guess now I have to extract it and simply link the new ndk-bundle to a particular directory and have it set with a PATH?
3. I noticed using version 5.1, the rake task says it can't find any platform, even though I have it. You can see it in the full trace - 
```bash
[INFO]	No Android platform found of version 5.1. Picking the latest one Android 8.1.0 available in machine
[INFO]	Using Android SDK build-tools: 27.0.3
```
It finds other SDK which I have installed from the Android Studio, but not 5.1. Why is that?

**Comment by alex-epifanoff** [comment]
2. just run rhodes-setup or modify rhobuild.yml ( located in rhodes gem installation dir ) for the new path to NDK. You don't have to change PATH.
3. platform search was updated recently. First it should look for specified platform and if it is not installed then fallback to any other installed platform starting from newest ones.
What you describe may be a bug, we'll check it.

**Comment by arjunmenon** [comment]
Hey
I just updated the yml file to the 15c ndk-build. I was successfully able to build the debug apk. :smile: 
Though it did not pick up the 5.1 version. Went ahead with the 8.1 version.

---
As a sidenote, my phone is Android 6.0
We can debug latest SDK in older versions of Android as well?

**Comment by alex-epifanoff** [comment]
We'll look into SDK version strating, it may be a bug.
Though you can build with latest SDK safely.

**Comment by alex-epifanoff** [comment]
Latest SDK/NDK are now supported
