### ISSUE TITLE
Gem shows no error but not working

### ISSUE THREAD

**Issue by arjunmenon** [rhomobile/rhodes#942]
Hey
I am using this [SSDP gem](https://github.com/daumiller/ssdp)
It depends on [`ipaddr`](https://github.com/ruby/ipaddr), `socket`
I have addedd `ipaddr` to the main Rhodes gem framework.
I modified the ssdp gem and included the contents inside its lib folder to the main framework as well.
Upon compilation of the app, it shows no error. Neither the adb log shows any error. But there is no output.
Wonder if the gem functionality is not supported or there is some system error?

The SSDP gem creates a UDP socket to listen to Upnp devices on a network.

That is my goal. To build a Upnp control point.
1. It requires access to native HTTP services, like sending requests over TCP/IP and UDP.
2. It also needs to serve music files from the phone over network.
3. It would also need to handle custom HTTP methods apart from GET/POST, like NOTIFY and SUBSCRIBE

As of now I am attempting task 1 and I dont see any errors in the adb.
This is the adb log - https://paste.ubuntu.com/26328082/
 
---
EDIT
In application.rb

```ruby
require 'socket'
require 'ipaddr'
require 'ssdp'
```

In index.erb

```ruby
<%= finder = SSDP::Consumer.new :timeout => 3 %> <br />
<%= result = finder.search :service => 'ssdp:all' %> <br />
<%= IPAddr.new('239.255.255.250').hton + IPAddr.new('0.0.0.0').hton %> <br />
<%= Rho::Network.hasNetwork %> <br />
<%= result %>
```

The above code returns nothing in the Rhodes app.
Except IPAddr, which returns gibberish symbols. Only that works.

---
![screenshot_2018-01-06-03-40-26-241_com rhomobile upnptest](https://user-images.githubusercontent.com/953959/34630824-bb617346-f293-11e7-982b-03d2bb7f3bce.png)

**Comment by rognar** [comment]
Hi Arjun,

This type of consulting is out of free support. Please purchase on of our paid support subscription to get it resolved.

Regards,
Konstantin Rybas
CEO at Tau Technologies Inc.

**Comment by arjunmenon** [comment]
Hey
Can you please link that here.
