### ISSUE TITLE
Poor performance with find conditions in v6.0.xx

### ISSUE THREAD

**Issue by jameslh** [rhomobile/rhodes#953]
Using `model.find(:all, :conditions => {...})` even with only one condition, there is considerable slowdown compared to `model.find(:all)`. 

Occurs in Win32 and RhoSimulator on Windows, though I would imagine it affects other platforms as well.

Performance worsens as the number of records increases. Here is some simple code to illustrate:

### Executes in 3.97 seconds
```data = Junk.find(:all, :conditions => {'junk_status' => '4'})```

### Executes in 0.17 seconds
```
data = Junk.find(:all)
data = data.select do |hash|
	hash.junk_status == '4'
end
```

**Comment by vmusulainen** [comment]
What kind of model you use PropertyBag or FixedScheme?
