### ISSUE TITLE
After 6.0.0 upgrade, RubyVM can't rescue Exception caused by ruby code evaluation

### ISSUE THREAD

**Issue by leonardofalk** [rhomobile/rhodes#961]
After upgrading our apps from 5.5.x to 6.0.30 (tested with 6.0.55 as well), part of our application responsible for evaluating math formulae aren't working properly. Consider the following example:

```ruby
begin
  eval('Date.today < nil') # will throw ArgumentError (comparison of Date with nil failed)
rescue => e
  nil
end
```

This is just a "naive" example, we actually have a Pascal grammar which we "transpile" to ruby using treetop and then evaluate. This works exactly as expected in rhodes 5.5.x, but after the upgrade the app crashes abruptly in runtime.

The only information in rholog.txt (at the moment of the error):

```
RubyVM| [NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
```

This happens only after the application is compiled, in Rhosimulator we get the expected behaviour.
Looks like a segmentation fault, but it could be something else. Perhaps the exception wasn't implemented ? That would make sense, because Rhosimulator runs with SO rubies and the final app is running on top of `.iseq` compiled files, but I couldn't figure it out so far.

I'd appreciate if someone could point me to any solution or where I should search for it.

**Comment by alex-epifanoff** [comment]
@leonardofalk we'll look into the issue.

**Comment by alex-epifanoff** [comment]
@leonardofalk please take a look at this PR https://github.com/rhomobile/rhodes/pull/962
Seems that Date module was not compatible with new VM. I have updated it, only works for iOS now.
We need to support all other platforms and perform all T&V processes before merging it to master for official builds.

**Comment by leonardofalk** [comment]
@alex-epifanoff Oh I'm very happy for that, I forgot to mention however that we've been trying to build for win32 and android. Looking at the PR it seems that you have implemented all date stuff and mapped dependencies back to iphone project's config, [win32 file](https://github.com/rhomobile/rhodes/blob/master/platform/win32/rubylib/rubylib.vcproj#L106) seems to apply files as well, if I wanted to try a fix for android, should I start [with this file](https://github.com/rhomobile/rhodes/blob/master/platform/android/build/CMakeLists.txt.erb) or it is a bit more complicated?

**Comment by alex-epifanoff** [comment]
@larsburgess no, for Android just change this file
https://github.com/rhomobile/rhodes/blob/master/platform/android/build/libruby_build.files
